version: '3.1'
services:
  aria2:
    build:
      dockerfile: Aria2.Dockerfile
    volumes:
      - ./downloads:/app/downloads
    ports:
      - 6801:6800
  web:
    build:
      dockerfile: App.Dockerfile
    ports:
      - 3000:3000
